name: frc_scout_app
description: "Offline-First FRC Scouting Application"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  csv: ^5.0.1
  provider: ^6.0.5
  googleapis: ^11.0.0  # For optional Sheets integration
  intl: ^0.18.1       # For date/time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/app_logo.png       # Splash screen logo
    - assets/images/login_screen_background.png       # Login screen background
    - assets/images/water.png
    - assets/csv/scouts.csv            # Scout roster
    - assets/csv/matches_flr.csv           # Match schedule